### ISSUE TITLE
missing device ids

### ISSUE THREAD

**Issue by lpfquest** [LEGO/lego-ble-wireless-protocol-docs#24]
Hi there,

thank you for publishing the spec. Following devices are reported but not listed:

technic hub:
- device 0x3C at 0x3D
- device 0x3C at 0x60
- device 0x39 at 0x61
- device 0x36 at 0x64

BOOST move hub:
- device 0x42 at 0x46

I'm missing these ids in section 3.8.4. IO Type ID ("List NOT guaranteed up to date!"). Does anyone know something about them? Where can I get information about those ids?

Thanks in advance

**Comment by marcrupprath** [comment]
Have a look here:
https://www.eurobricks.com/forum/index.php?/forums/topic/162288-powered-up-a-tear-down/&page=23

Look for answer of February 12 from  >>Mr Hobbles<<:
"Type 3C is a temperature sensor (there are two of them, don't know where they're located), 39 is the accelerometer, 3A is the gyro, 3B is the tilt sensor, and 36 is the gesture sensor. I added support for the accelerometer, gyro, and tilt sensor modes node-poweredup,"

There are some links with usefull code also there

**Comment by lpfquest** [comment]
Thank you so much, that's it :-)
